spring:
  application:
    name: CustomerService
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/db
server:
  port: 8082


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetch-registry: true

